tap "homebrew/cask"
tap "github/gh"
tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
cask_args appdir: "/Applications"

# brew "postgresql"
brew "ack"
brew "asdf"
brew "autojump"
brew "bat"
brew "brew-cask-completion"
brew "burntsushi/ripgrep/ripgrep-bin"
brew "coreutils"
brew "eslint"
brew "exercism"
brew "fzf"
brew "gh"
brew "git"
brew "gpg"
brew "navi"
brew "neovim"
brew "openssl"
brew "reattach-to-user-namespace"
brew "redis"
brew "tmux"
brew "yarn"
brew "zsh"
brew "zsh-completions"

cask "1password-cli"
cask "github"

# mas "1Password 7", id: 1333542190
# mas "Slack", id: 803453959
# mas "Xcode", id: 497799835
